baseURL = 'https://npmlab.netlify.app/'
languageCode = 'en-us'
title = 'Neuromotor Plasticity and Modulation Lab'
theme = 'neuroplasticity'
[pagination]
  pagerSize = 10

[params]
  description = 'Improving neuromotor function for people with neurological conditions such as spinal cord injury and stroke.'
  author = 'Jia Liu'
  institution = 'The Ohio State University'
  department = 'School of Health and Rehabilitation Sciences, College of Medicine'
  disclaimer = 'Opinions expressed on this site are those of the author(s) and do not represent the views of The Ohio State University.'

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Research'
    url = '/research/'
    weight = 2
  [[menu.main]]
    name = 'Publications'
    url = '/publications/'
    weight = 3
  [[menu.main]]
    name = 'Team'
    url = '/team/'
    weight = 4
  [[menu.main]]
    name = 'News'
    url = '/news/'
    weight = 5
  [[menu.main]]
    name = 'Openings'
    url = '/join/'
    weight = 6

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
